# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import badge_rc


class Ui_Mwbreath(object):
    def setupUi(self, Mwbreath):
        # 主窗体对象调用setupUi方法，对QMainWindow对象进行设置
        Mwbreath.setObjectName("Mwbreath")
        Mwbreath.resize(1195, 700)
        Mwbreath.setAutoFillBackground(False)
        Mwbreath.setStyleSheet("background:rgb(255, 255, 255)")
        # 设置UI中央标题‘Demo  System  for  Breath  Detecting’
        self.systemtext = QtWidgets.QLabel(Mwbreath)
        self.systemtext.setGeometry(QtCore.QRect(370, 140, 501, 81))
        self.systemtext.setMinimumSize(QtCore.QSize(351, 0))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.systemtext.setFont(font)
        self.systemtext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.systemtext.setStyleSheet("color: rgb(0, 0, 0)\n"
                                      "font： 16pt \"Times New Roman\";")
        self.systemtext.setObjectName("systemtext")
        # 设置学校图标
        self.schoolicon = QtWidgets.QLabel(Mwbreath)
        self.schoolicon.setGeometry(QtCore.QRect(60, 40, 111, 111))
        self.schoolicon.setText("")
        self.schoolicon.setPixmap(QtGui.QPixmap(":/icon/image/BUPT_badge.jfif"))
        self.schoolicon.setScaledContents(True)
        self.schoolicon.setObjectName("schoolicon")
        self.schooltext = QtWidgets.QLabel(Mwbreath)
        self.schooltext.setGeometry(QtCore.QRect(190, 60, 501, 81))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(16)
        self.schooltext.setFont(font)
        self.schooltext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.schooltext.setStyleSheet("color: rgb(17, 84, 182)")
        self.schooltext.setLineWidth(2)
        self.schooltext.setMidLineWidth(1)
        self.schooltext.setObjectName("schooltext")
        # 设置 about us 按钮
        self.aboutbutton = QtWidgets.QPushButton(Mwbreath)
        self.aboutbutton.setGeometry(QtCore.QRect(880, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.aboutbutton.setFont(font)
        self.aboutbutton.setStyleSheet(
            '''QPushButton{}QPushButton:hover{background:rgb(255,225,132);;}''')
        self.aboutbutton.setObjectName("aboutbutton")
        # 设置 help 按钮
        self.helpbutton = QtWidgets.QPushButton(Mwbreath)
        self.helpbutton.setGeometry(QtCore.QRect(1040, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.helpbutton.setFont(font)
        self.helpbutton.setStyleSheet(
            '''QPushButton{}QPushButton:hover{background:rgb(255,225,132);;}''')
        self.helpbutton.setObjectName("helpbutton")
        # 设置wave展示的UI界面
        self.waveUI = QtWidgets.QGroupBox(Mwbreath)
        self.waveUI.setGeometry(QtCore.QRect(630, 240, 511, 391))
        self.waveUI.setTitle("")
        self.waveUI.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.waveUI.setFlat(False)
        self.waveUI.setCheckable(False)
        self.waveUI.setObjectName("waveUI")
        self.wavetext = QtWidgets.QLabel(self.waveUI)
        self.wavetext.setGeometry(QtCore.QRect(160, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.wavetext.setFont(font)
        self.wavetext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wavetext.setObjectName("wavetext")
        # wave设置off和on按钮
        self.on2button = QtWidgets.QPushButton(Mwbreath)
        self.on2button.setGeometry(QtCore.QRect(1110, 600, 31, 28))
        self.on2button.setObjectName("on2button")
        self.on2button.setStyleSheet(
            '''QPushButton{background:rgb(0,0,0,0);border-radius:5px;}QPushButton:hover{background:rgb(255,225,132);}''')
        # 设置cvUI界面
        self.cvUI = QtWidgets.QLabel(Mwbreath)
        self.cvUI.setGeometry(QtCore.QRect(60, 240, 511, 391))
        self.cvUI.setSizeIncrement(QtCore.QSize(2, 2))
        self.cvUI.setText("")
        self.cvUI.setObjectName("cvUI")
        self.cvtext = QtWidgets.QLabel(Mwbreath)
        self.cvtext.setGeometry(QtCore.QRect(240, 250, 161, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.cvtext.setFont(font)
        self.cvtext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cvtext.setObjectName("cvtext")
        self.cvtext.setStyleSheet('QLabel{background:rgb(225,225,225,70);}')
        # cv设置off和on按钮
        self.onbutton = QtWidgets.QPushButton(Mwbreath)
        self.onbutton.setGeometry(QtCore.QRect(530, 600, 31, 28))
        self.onbutton.setObjectName("onbutton")
        self.onbutton.setStyleSheet(
            '''QPushButton{background:rgb(0,0,0,0);border-radius:5px;}QPushButton:hover{background:rgb(255,225,132);}''')

        # 完成所有的控件的文字设置
        self.retranslateUi(Mwbreath)

        self.aboutbutton.clicked.connect(Mwbreath.on_ab)
        self.helpbutton.clicked.connect(Mwbreath.on_hb)
        self.onbutton.clicked.connect(Mwbreath.on_cv)
        self.on2button.clicked.connect(Mwbreath.on_wave)
        # 自动链接到所有的槽函数
        QtCore.QMetaObject.connectSlotsByName(Mwbreath)

    def retranslateUi(self, Mwbreath):
        _translate = QtCore.QCoreApplication.translate
        Mwbreath.setWindowTitle(_translate("Mwbreath", "Demo system for breath detecting"))
        self.wavetext.setText(_translate("Mwbreath", "Wi-Fi感知呼吸波形"))
        self.systemtext.setText(_translate("Mwbreath", "Demo  System  for  Breath  Detecting"))
        self.schooltext.setText(_translate("Mwbreath", "Beijing University of Posts and Telecomunications \n"
                                                       "                             NSCA Lab"))
        self.aboutbutton.setText(_translate("Mwbreath", "about us"))
        self.helpbutton.setText(_translate("Mwbreath", "help"))
        self.cvtext.setText(_translate("Mwbreath", "摄像头实时画面"))
        self.onbutton.setText(_translate("Mwbreath", "on"))
        self.on2button.setText(_translate("Mwbreath", "on"))
